# Generated by Django 4.2.4 on 2023-08-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryweight',
            name='weight',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
